### ISSUE TITLE
flock error: bad number

### ISSUE THREAD

**Issue by matthewpersico** [ccarpita/kvstore#1]
All attempts to use kvstore result in the error 

    flock: bad number: '/home/Matthew/.kvstore/testfile.lock'

A little digging around via `man flock` reveals that the call 

    flock -x -w 5 "$lockfile"

isn't going to work.  You have to call `flock` with some kind of command OR replace the `$lockfile` with a file descriptor number. This is from the man page for `flock` on two different Linux systems. Here is a copy from the net:

[http://www.tutorialspoint.com/unix_commands/flock.htm](url)

Please advise.

**Comment by ccarpita** [comment]
He @matthewpersico, this is a good find, and points to the need for Linux CI as I've only been running this on OSX.  I think the preferable thing is to create a FD as the output of a subshell and flock it.  I'll put something together and CC you, if you don't mind giving it a try.

**Comment by matthewpersico** [comment]
Not a problem. In fact, I've done quite a bit of work on my end that I wanted to shake out for another few days before passing along. As a preview:

- I split the file into individual functions that I then autoload so that every time you run kvstore, you do not have to reparse all the functions. That means, of course, that someplace in your start up, you have to run 'autoload' on the functions. Now I know what you are thinking, "autoload is a ksh thing, not bash". Weeeeeeell, I found an old autoload implementation in the bash source and then extensively modified/enhanced to make it useful, in my opinion. Anyway, given that autoload in bash is not widely used, I willnot be sending you those changes. However, I present it as background to some of the other changes I made.

- All functions that start with _ now start with `_kvstore_`. Not super-critical if all are in one script, but very critical for avoiding namespace conflicts if you use them as loaded functions.
- `kvstore ls` now takes no arguments and only lists the stores
- `kvstore keys` lists the keys in a store (replaces `kvstore ls <namespace>`)
- `kvstore vals` lists the values in a store (replaces `kvstore lsval <namespace>`)
- I eliminated `_kvstore_lock` and just put the locking code into `_kvstore_lock_then`. I left the `lockfile` implemenation as is (lock, run, rm lockfile), but modified the flock implementation to use flock with a file descriptor. I am not too sure if that makes things better or worse, so I am going to look at your latest change and see if that works better.

**Comment by ccarpita** [comment]
The internal namespacing changes and API changes sound very reasonable, and I'm not too concerned about breaking changes since it's not a commonly followed/forked module.  We should at least add something to the README to the effect that we are on version 2 and update usage doc, with a link to the old usage docs (or inline).   This is just in case we have someone pulling in this script remotely as part of a workflow, and unsure as to why it's now throwing errors after a breaking change.

**Comment by matthewpersico** [comment]
When you merge your flock fix into your master, I am ready with 12 distinct commits:

1. Namespace fixup
1. New functions `keys` and `values` replacing `ls <namespace>` and `lsval <namespace>`, respectively.
1. A fix for `ls` so that it does not show the lock files.
1. Added a `version` command. Set it to 2.0.
1. Added `drop <namespace>` command.
1. Various formatting 'nits'.
1. Added a `load` command that does nothing so that you can do `source /PATH/TO/kvstore.ksh` in your profile file and all the functions are loaded into environment space, if you are into that sort of thing.
1. Added a `dump <namespace>` command that just `cat`s the file to list all keys and values.
1. Added an `lsinfo` command which is `ls` plus entry count, byte size and last write time.
1. Added a `-f` flag to the `mv` command so that the move will overwrite an existing `to-key`.
1. Added a `-v` flag to `dump` which adds the namespace as a header to the output.
1. More nits.

You want these as 12 commits in one PR or 12 commits in 12 PRs? If the latter than I will need to submit each one, one at a time after you accept and merge the prior one.

Of course, you could also want this all squished down into one commit, but then I think you lose the sense of each change,

Your repo, your code; your call.

Let me know.
