### ISSUE TITLE
Add all commands to command-line completion

### ISSUE THREAD

**Issue by amper5and** [ccarpita/kvstore#10]
First off all, I really like this little tool. Thanks for making it!

I was wondering whether you're planning to add the rest of the commands for auto-completion? I think it would be a great addition. I would love to do it, but I'm just learning shell programming, so I'm bound to screw it up. Thanks!

**Comment by matthewpersico** [comment]
See PR #11

**Comment by matthewpersico** [comment]
Closed by #11

**Comment by ccarpita** [comment]
Fixed by https://github.com/ccarpita/kvstore/pull/11
