### ISSUE TITLE
mv does not have a force mode

### ISSUE THREAD

**Issue by matthewpersico** [ccarpita/kvstore#6]
Currently, you cannot do a mv if the target key exists. I can easily add that functionality with a -f flag to the mv command; that's not really the issue I'm concerned about. What I am concerned about is placement.

In traditional UNIX, the options come before the args, so we'd end up with:

    kvstore mv -f namespace oldkey newkey

But that goes against kvstore format where the namespace is ALWAYS the field after the command. We could break with tradition and allow

    kvstore mv namespace oldkey newkey -f

which would be much easier on everyone's fingers; typically you'd type a mv command, see that it fails, do a command recall and then tack the -f on the end instead of having to arrow back or do some kind of other finger contortions to stick the -f up in the front of the recalled command. But, people might look at you weird (because it's your name on the software, not mine. :-) )

So, which way do you want me to code it - traditional options up front or radical options at end?

**Comment by ccarpita** [comment]
I would say traditional placement makes the most sense, and flags can be extracted by iterating through the args and capturing any that begin with `-*`.  We might want to do a parse expression at the beginning that sets variables like "$KVSTORE_COMMAND", "$KVSTORE_NS", "@KVSTORE_ARGS", "$KVSTORE_FLAG_F", etc to make this more standard

**Comment by matthewpersico** [comment]
Hmm. We're going to have to push all option and args processing into each function. Each one will have different options and its probably best to let each one deal with what's valid for it and what's not.

Give me a few days to pull that together. Oh and I have gotten away from using getopt and getopts because you never know which one will be available, one of them doesn't process long strings and I can't stand that long opts need -- while short ones need -. I do my own processing and looping with only one real hard fast difference from regular processing: no single option ganging. So -f -t -x are ok but -ftx is not. Seems like a small price to pay.

**Comment by matthewpersico** [comment]
Just a note. Real life has taken over for the next week or so. I'll let you know when I get a chance to work on this

**Comment by ccarpita** [comment]
No problem, I have been away as well, but whenever you have something ready I can review

**Comment by matthewpersico** [comment]
mv STILL does not have a force mode. :-) But I have added some other commands, clearing the decks for adding the -f on the next pull. In the meantime, check out pull #7 .

**Comment by matthewpersico** [comment]
Ugh - Totally forgot about this. It's on my disk ready to PR. I'll do this tonight (2017/09/07)

**Comment by matthewpersico** [comment]
Pull #11 moves the options to start of command list, where they should be.

**Comment by ccarpita** [comment]
Added by https://github.com/ccarpita/kvstore/pull/11
