### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by amper5and** [ccarpita/kvstore#9]
I get

    line 410: syntax error near unexpected token `)'
    line 410: `    load)'

Any thoughts?

**Comment by amper5and** [comment]
Ok, it seems you forgot `;;` before that `load)`. Adding that fixes it for me.

**Comment by matthewpersico** [comment]
See PR #11

**Comment by ccarpita** [comment]
Fixed by https://github.com/ccarpita/kvstore/pull/11
